"""add_last_unanswered_message_id_to_patients

Revision ID: 98da4ecb7f88
Revises: 8e246e2060d9
Create Date: 2026-03-22 22:47:34.717582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98da4ecb7f88'
down_revision: Union[str, Sequence[str], None] = '8e246e2060d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('last_unanswered_message_id', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('phase_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedule_events', sa.Column('message', sa.String(), nullable=True))
    with op.batch_alter_table('schedule_events') as batch_op:
        batch_op.alter_column('event_type',
                   existing_type=sa.VARCHAR(length=5),
                   type_=sa.Enum('DAY_2', 'DAY_5', 'DAY_7', 'REMINDER', name='eventtype'),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_events') as batch_op:
        batch_op.alter_column('event_type',
                   existing_type=sa.Enum('DAY_2', 'DAY_5', 'DAY_7', 'REMINDER', name='eventtype'),
                   type_=sa.VARCHAR(length=5),
                   existing_nullable=False)
    op.drop_column('schedule_events', 'message')
    op.drop_column('patients', 'phase_updated_at')
    op.drop_column('patients', 'last_unanswered_message_id')
    # ### end Alembic commands ###
